#- name: upgrade all packages
#  yum: name=* state=latest
#  tags: basics
- name: be sure basic packages are installed
  yum: name={{item}} state=present enablerepo=epel
  with_items:
        - ssh
        - fail2ban
        - postfix
        - nscd
        - ntp
        - vim
        - tree
        - iftop
        - iotop
        - atsar
  tags: basics

