- name: be sure basic packages are installed
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
        - ssh
        - fail2ban
        - postfix
        - nscd
        - ntp
        - vim
        - tree
        - iftop
        - iotop
        - atsar
        - python-mysqldb
        - python-pycurl
        - python-apt
        - python-passlib
        - python-httplib2
  tags: basics

- name: update all packages to the latest version
  apt: upgrade=dist

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp
